# Generated by Django 4.2.8 on 2024-04-17 15:23

from django.db import migrations, models
import intern_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0003_alter_reftoken_ref_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reftoken',
            name='exp_date',
            field=models.DateField(default=intern_app.utils.define_exp_date, verbose_name='Дата истечения срока'),
        ),
    ]
